# Generated by Django 3.2 on 2023-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chemist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_name', models.CharField(max_length=500)),
                ('smiles', models.CharField(max_length=500)),
                ('user_message', models.CharField(max_length=500)),
                ('matches', models.CharField(max_length=500)),
                ('posting_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatternMatchingInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.TextField()),
                ('input_format', models.CharField(max_length=16)),
                ('input_max_nof_molecules_allowed', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatternMatchingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('error', models.TextField(null=True)),
                ('error_detailed', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('input_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_chemist.patternmatchinginputmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='hierarchy',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='PatternMatchingOutputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_json', models.JSONField()),
                ('parent_pattern_matching_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smart_chemist.patternmatchingjob')),
            ],
        ),
        migrations.AddField(
            model_name='patternmatchingjob',
            name='output_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_chemist.patternmatchingoutputmodel'),
        ),
        migrations.AddField(
            model_name='patternmatchinginputmodel',
            name='parent_pattern_matching_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smart_chemist.patternmatchingjob'),
        ),
    ]
