# Generated by Django 4.2.1 on 2023-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chemist', '0002_auto_20230519_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='matches',
            field=models.JSONField(),
        ),
    ]
