# Generated by Django 4.2.1 on 2023-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chemist', '0003_alter_bugreport_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
