# Generated by Django 4.2.1 on 2023-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chemist', '0004_bugreport_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedpattern',
            name='index_file',
            field=models.IntegerField(default=0),
        ),
    ]
