# Generated by Django 3.2.5 on 2025-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_chemist', '0005_annotatedpattern_index_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedpattern',
            name='heavy_atoms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_carbon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_halogens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_nitrogens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_other_atom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_oxygen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_phosphor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='n_sulfur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotatedpattern',
            name='num_rings',
            field=models.IntegerField(default=0),
        ),
    ]
